seed: 42
surrogate_seed: 1452
dataset: "covertype"
type: "tabular"
task: "classification"
path:  "../datasets/csv/covtype.csv"
checkpoint_path: "./checkpoint/covertype.pth"
epochs: 60
replace_aux_with_noise: False

client_device: "cuda"
server_device: "cuda"

bottom_model_layers: 3
bottom_model_output_dim: 128
cosine_alpha: 0.3
intra_beta: 0.2
task_theta: 0.5

defense: "no"
noise_std: 0.1
pruning_ratio: 0.9

lr: 1e-3
bs: 256

lr_ms: 1e-3
bs_ms: 256
alpha_ms: 0.5
beta_ms: 0.5

lr_dr: 1e-2
bs_dr: 1024

contrastive_hidden_dim: 128
contrastive_output_dim: 256
contrastive_projection_dim: 10
contrastive_epochs: 50

contrastive_noise_mean: 0.0
contrastive_noise_std: 0.1
contrastive_dropout_rate: 0.1

bs_contrastive: 256
lr_contrastive: 1e-3

knn_k: null
hnsw_m: 16
hnsw_ef_construction: 200
hnsw_ef_search: 50

top_model_layers: 3
contrastive_temp: 0.1
tau_soft: 2.0
knn_ratio: 0.1
contrastive_encoder_layers: 3
optimizer_ms: Adam
optimizer_contrastive: Adam
